/**
 * Drizzle client singleton for the Peri-Fuse metadata database (langfuse.db),
 * backed by better-sqlite3.
 *
 * Migrated from Prisma. The database file is resolved from DATABASE_URL (lite
 * mode), mirroring the previous PrismaClientSingleton path resolution. Tables
 * are created on demand via ensureSchema(), which applies the committed
 * drizzle migration SQL under <package-root>/drizzle — no `prisma db push`.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { env } from "node:process";
import Database from "better-sqlite3";
import { drizzle, type BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema/index.js";

export type Db = BetterSQLite3Database<typeof schema>;

let _sqlite: Database.Database | null = null;
let _db: Db | null = null;

/**
 * Resolve the SQLite file path from DATABASE_URL. Relative `file:` paths are
 * resolved against process.cwd() so the DB is found regardless of the working
 * directory (same behaviour as the previous Prisma datasource resolution).
 */
function resolveDbPath(): string {
  const raw = env.DATABASE_URL ?? "file:./.langfuse/langfuse.db";
  const file = raw.startsWith("file:") ? raw.slice("file:".length) : raw;
  return path.isAbsolute(file) ? file : path.resolve(process.cwd(), file);
}

function getSqlite(): Database.Database {
  if (_sqlite) return _sqlite;
  const dbPath = resolveDbPath();
  fs.mkdirSync(path.dirname(dbPath), { recursive: true });
  _sqlite = new Database(dbPath);
  // Match the previous Prisma connection settings.
  _sqlite.pragma("journal_mode = WAL");
  _sqlite.pragma("busy_timeout = 5000");
  _sqlite.pragma("foreign_keys = ON");
  return _sqlite;
}

export function getDb(): Db {
  if (!_db) {
    _db = drizzle(getSqlite(), { schema });
  }
  return _db;
}

/** Close the underlying SQLite connection (used on shutdown). */
export function closeDb(): void {
  if (_sqlite) {
    _sqlite.close();
    _sqlite = null;
    _db = null;
  }
}

let _schemaReady = false;

/**
 * Locate the package root (the folder containing package.json) by walking up
 * from this module. Works both in dev (src/db/client.ts) and compiled output
 * (dist/src/db/client.ts).
 */
function findPackageRoot(): string {
  let dir = __dirname;
  for (let i = 0; i < 8; i++) {
    if (fs.existsSync(path.join(dir, "package.json"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return __dirname;
}

/**
 * Read all committed migration SQL files (drizzle/*.sql) in lexicographic
 * order. The file name is generated by drizzle-kit, so we discover it rather
 * than hard-coding it.
 */
function readMigrationSql(): string {
  const drizzleDir = path.join(findPackageRoot(), "drizzle");
  const files = fs
    .readdirSync(drizzleDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  if (files.length === 0) {
    throw new Error(`No migration SQL found in ${drizzleDir}`);
  }
  return files.map((f) => fs.readFileSync(path.join(drizzleDir, f), "utf8")).join("\n");
}

/**
 * Returns true if the database already has the metadata tables (schema
 * applied by a previous boot). Used to make ensureSchema() idempotent so
 * restarting against an existing database does not re-run CREATE TABLE.
 */
function schemaAlreadyApplied(sqlite: Database.Database): boolean {
  try {
    const row = sqlite
      .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='organizations'")
      .get();
    return !!row;
  } catch {
    return false;
  }
}

/**
 * Create all metadata tables if they do not exist. Executes the committed
 * drizzle migration SQL against a (typically fresh) database. Idempotent:
 * skips entirely when the tables already exist (restart with existing DB).
 */
export function ensureSchema(): void {
  if (_schemaReady) return;
  const sqlite = getSqlite();
  if (schemaAlreadyApplied(sqlite)) {
    _schemaReady = true;
    return;
  }
  const sql = readMigrationSql();
  for (const raw of sql.split("--> statement-breakpoint")) {
    const stmt = raw.trim();
    if (stmt) sqlite.exec(stmt);
  }
  _schemaReady = true;
}
