import { sql } from "drizzle-orm";
import {
  blob,
  index,
  integer,
  primaryKey,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

export const traces = sqliteTable(
  "traces",
  {
    id: text("id").notNull(),
    projectId: text("project_id").notNull(),
    timestamp: text("timestamp").notNull().default(sql`(datetime('now'))`),
    name: text("name"),
    userId: text("user_id"),
    metadata: text("metadata").default(sql`'{}'`),
    release: text("release"),
    version: text("version"),
    public: integer("public").default(sql`0`),
    bookmarked: integer("bookmarked").default(sql`0`),
    tags: text("tags").default(sql`'[]'`),
    input: blob("input", { mode: "buffer" }),
    inputCodec: integer("input_codec").notNull().default(sql`0`),
    inputRawSize: integer("input_raw_size"),
    output: blob("output", { mode: "buffer" }),
    outputCodec: integer("output_codec").notNull().default(sql`0`),
    outputRawSize: integer("output_raw_size"),
    sessionId: text("session_id"),
    createdAt: text("created_at").notNull().default(sql`(datetime('now'))`),
    updatedAt: text("updated_at").notNull().default(sql`(datetime('now'))`),
    eventTs: text("event_ts").notNull().default(sql`(datetime('now'))`),
    isDeleted: integer("is_deleted").default(sql`0`),
    environment: text("environment").default(sql`'default'`),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.id] }),
    index("idx_traces_project_timestamp").on(table.projectId, table.timestamp),
    index("idx_traces_project_session").on(table.projectId, table.sessionId),
    index("idx_traces_project_name").on(table.projectId, table.name),
    index("idx_traces_deleted_session").on(
      table.projectId,
      table.isDeleted,
      table.sessionId,
      table.timestamp,
      table.userId,
      table.environment,
      table.tags,
    ),
    index("idx_traces_deleted_user").on(
      table.projectId,
      table.isDeleted,
      table.userId,
      table.timestamp,
      table.environment,
    ),
  ],
);

export const observations = sqliteTable(
  "observations",
  {
    id: text("id").notNull(),
    projectId: text("project_id").notNull(),
    traceId: text("trace_id"),
    parentObservationId: text("parent_observation_id"),
    type: text("type").notNull().default(sql`'SPAN'`),
    name: text("name"),
    startTime: text("start_time").notNull().default(sql`(datetime('now'))`),
    endTime: text("end_time"),
    metadata: text("metadata").default(sql`'{}'`),
    model: text("model"),
    input: blob("input", { mode: "buffer" }),
    inputCodec: integer("input_codec").notNull().default(sql`0`),
    inputRawSize: integer("input_raw_size"),
    output: blob("output", { mode: "buffer" }),
    outputCodec: integer("output_codec").notNull().default(sql`0`),
    outputRawSize: integer("output_raw_size"),
    level: text("level").default(sql`'DEFAULT'`),
    statusMessage: text("status_message"),
    completionStartTime: text("completion_start_time"),
    promptId: text("prompt_id"),
    promptName: text("prompt_name"),
    promptVersion: integer("prompt_version"),
    modelParameters: text("model_parameters").default(sql`'{}'`),
    usageDetails: text("usage_details").default(sql`'{}'`),
    costDetails: text("cost_details").default(sql`'{}'`),
    providedUsageDetails: text("provided_usage_details").default(sql`'{}'`),
    providedCostDetails: text("provided_cost_details").default(sql`'{}'`),
    totalCost: real("total_cost"),
    version: text("version"),
    createdAt: text("created_at").notNull().default(sql`(datetime('now'))`),
    updatedAt: text("updated_at").notNull().default(sql`(datetime('now'))`),
    eventTs: text("event_ts").notNull().default(sql`(datetime('now'))`),
    isDeleted: integer("is_deleted").default(sql`0`),
    environment: text("environment").default(sql`'default'`),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.id] }),
    index("idx_observations_project_trace").on(table.projectId, table.traceId),
    index("idx_observations_project_start").on(table.projectId, table.startTime),
    index("idx_observations_project_type").on(table.projectId, table.type),
    index("idx_obs_deleted_name").on(table.projectId, table.isDeleted, table.name),
    index("idx_obs_start_cost").on(
      table.projectId,
      table.isDeleted,
      table.startTime,
      table.totalCost,
    ),
    index("idx_obs_type_start_model").on(
      table.projectId,
      table.isDeleted,
      table.type,
      table.startTime,
      table.model,
      table.totalCost,
    ),
    index("idx_obs_start_level").on(table.projectId, table.isDeleted, table.startTime, table.level),
    index("idx_obs_error_start").on(
      table.projectId,
      table.isDeleted,
      table.level,
      table.startTime,
      table.id,
    ),
    index("idx_obs_type_level_start").on(
      table.projectId,
      table.isDeleted,
      table.type,
      table.level,
      table.startTime,
    ),
  ],
);

export const traceMetrics = sqliteTable(
  "trace_metrics",
  {
    projectId: text("project_id").notNull(),
    traceId: text("trace_id"),
    userId: text("user_id"),
    sessionId: text("session_id"),
    obsCount: integer("obs_count").default(sql`0`),
    totalCost: real("total_cost").default(sql`0`),
    inputCost: real("input_cost").default(sql`0`),
    outputCost: real("output_cost").default(sql`0`),
    inputTokens: integer("input_tokens").default(sql`0`),
    outputTokens: integer("output_tokens").default(sql`0`),
    totalTokens: integer("total_tokens").default(sql`0`),
    cachedTokens: integer("cached_tokens").default(sql`0`),
    cacheCreationTokens: integer("cache_creation_tokens").default(sql`0`),
    grossInputTokens: integer("gross_input_tokens").default(sql`0`),
    timestamp: text("timestamp"),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.traceId] }),
    index("idx_trace_metrics_session").on(table.projectId, table.sessionId),
    index("idx_trace_metrics_user").on(table.projectId, table.userId),
    index("idx_trace_metrics_ts").on(table.projectId, table.timestamp),
  ],
);

export const dailyStats = sqliteTable(
  "daily_stats",
  {
    projectId: text("project_id").notNull(),
    day: text("day").notNull(),
    traces: integer("traces").notNull().default(sql`0`),
    usersJson: text("users_json").notNull().default(sql`'[]'`),
    observations: integer("observations").notNull().default(sql`0`),
    generations: integer("generations").notNull().default(sql`0`),
    errors: integer("errors").notNull().default(sql`0`),
    warnings: integer("warnings").notNull().default(sql`0`),
    debugs: integer("debugs").notNull().default(sql`0`),
    tokens: integer("tokens").notNull().default(sql`0`),
    cachedTokens: integer("cached_tokens").notNull().default(sql`0`),
    grossInputTokens: integer("gross_input_tokens").notNull().default(sql`0`),
    scoresCount: integer("scores_count").notNull().default(sql`0`),
    scoresValCount: integer("scores_val_count").notNull().default(sql`0`),
    scoreSum: real("score_sum").notNull().default(sql`0`),
    latCount: integer("lat_count").notNull().default(sql`0`),
    latSumMs: real("lat_sum_ms").notNull().default(sql`0`),
    latHist: text("lat_hist").notNull().default(sql`'[]'`),
    updatedAt: text("updated_at").notNull().default(sql`(datetime('now'))`),
  },
  (table) => [primaryKey({ columns: [table.projectId, table.day] })],
);

export const dailyModelStats = sqliteTable(
  "daily_model_stats",
  {
    projectId: text("project_id").notNull(),
    day: text("day").notNull(),
    model: text("model").notNull(),
    observations: integer("observations").notNull().default(sql`0`),
    tokens: integer("tokens").notNull().default(sql`0`),
    latCount: integer("lat_count").notNull().default(sql`0`),
    latSumMs: real("lat_sum_ms").notNull().default(sql`0`),
    latHist: text("lat_hist").notNull().default(sql`'[]'`),
  },
  (table) => [primaryKey({ columns: [table.projectId, table.day, table.model] })],
);

export const scores = sqliteTable(
  "scores",
  {
    id: text("id").notNull(),
    projectId: text("project_id").notNull(),
    traceId: text("trace_id"),
    observationId: text("observation_id"),
    name: text("name").notNull(),
    value: real("value"),
    stringValue: text("string_value"),
    source: text("source").notNull().default(sql`'API'`),
    comment: text("comment"),
    authorUserId: text("author_user_id"),
    configId: text("config_id"),
    dataType: text("data_type").notNull().default(sql`'NUMERIC'`),
    timestamp: text("timestamp").notNull().default(sql`(datetime('now'))`),
    createdAt: text("created_at").notNull().default(sql`(datetime('now'))`),
    updatedAt: text("updated_at").notNull().default(sql`(datetime('now'))`),
    eventTs: text("event_ts").notNull().default(sql`(datetime('now'))`),
    isDeleted: integer("is_deleted").default(sql`0`),
    environment: text("environment").default(sql`'default'`),
    queueId: text("queue_id"),
    metadata: text("metadata").default(sql`'{}'`),
    sessionId: text("session_id"),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.id] }),
    index("idx_scores_project_ts").on(table.projectId, table.timestamp, table.id),
    index("idx_scores_project_trace").on(table.projectId, table.traceId),
    index("idx_scores_project_name").on(table.projectId, table.name),
  ],
);

export const datasetRunItems = sqliteTable(
  "dataset_run_items",
  {
    id: text("id").notNull(),
    projectId: text("project_id").notNull(),
    datasetRunId: text("dataset_run_id").notNull(),
    datasetItemId: text("dataset_item_id").notNull(),
    datasetId: text("dataset_id").notNull(),
    traceId: text("trace_id").notNull(),
    observationId: text("observation_id"),
    error: text("error"),
    datasetItemValidFrom: text("dataset_item_valid_from"),
    datasetVersion: text("dataset_version"),
    createdAt: text("created_at").notNull().default(sql`(datetime('now'))`),
    updatedAt: text("updated_at").notNull().default(sql`(datetime('now'))`),
    eventTs: text("event_ts").notNull().default(sql`(datetime('now'))`),
    isDeleted: integer("is_deleted").default(sql`0`),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.id] }),
    index("idx_dri_project_run").on(table.projectId, table.datasetRunId),
    index("idx_dri_project_item").on(table.projectId, table.datasetItemId),
    index("idx_dri_project_trace").on(table.projectId, table.traceId),
  ],
);

export const searchTexts = sqliteTable(
  "search_texts",
  {
    textId: integer("text_id").primaryKey(),
    projectId: text("project_id").notNull(),
    contentHash: text("content_hash").notNull(),
    chunkNo: integer("chunk_no").notNull(),
    displayText: text("display_text").notNull(),
    normalizedText: text("normalized_text").notNull(),
    projectScope: text("project_scope").notNull(),
    indexVersion: integer("index_version").notNull().default(sql`1`),
  },
  (table) => [
    uniqueIndex("search_texts_project_id_content_hash_chunk_no_index_version_unique").on(
      table.projectId,
      table.contentHash,
      table.chunkNo,
      table.indexVersion,
    ),
  ],
);

export const searchTrigrams = sqliteTable(
  "search_trigrams",
  {
    projectId: text("project_id").notNull(),
    gram: text("gram").notNull(),
    textId: integer("text_id").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.gram, table.textId] }),
    index("idx_search_trigrams_text").on(table.projectId, table.textId),
  ],
);

export const searchOccurrences = sqliteTable(
  "search_occurrences",
  {
    occurrenceId: text("occurrence_id").primaryKey(),
    projectId: text("project_id").notNull(),
    textId: integer("text_id").notNull(),
    sourceKind: text("source_kind").notNull(),
    sourceId: text("source_id").notNull(),
    traceId: text("trace_id"),
    role: text("role").notNull(),
    field: text("field").notNull(),
    messageOrder: integer("message_order").notNull(),
    chunkNo: integer("chunk_no").notNull(),
    sourceVersion: integer("source_version").notNull(),
    eventTime: text("event_time").notNull(),
    sessionId: text("session_id"),
    displayStart: integer("display_start").notNull().default(sql`0`),
    displayEnd: integer("display_end").notNull().default(sql`0`),
  },
  (table) => [
    index("idx_search_occ_window").on(
      table.projectId,
      table.eventTime,
      table.occurrenceId,
      table.textId,
    ),
    index("idx_search_occ_source").on(table.projectId, table.sourceKind, table.sourceId),
    index("idx_search_occ_text").on(table.projectId, table.textId),
    index("idx_search_occ_context").on(
      table.projectId,
      table.sourceKind,
      table.sourceId,
      table.sourceVersion,
      table.messageOrder,
      table.chunkNo,
    ),
  ],
);
