import { defineRelations } from "drizzle-orm";
import * as schema from "./schema.js";

export const databaseRelations = defineRelations(schema, (relations) => ({
  account: {
    user: relations.one.users({ from: [relations.account.userId], to: [relations.users.id] }),
  },
  users: {
    accounts: relations.many.account({ from: [relations.users.id], to: [relations.account.userId] }),
    sessions: relations.many.session({ from: [relations.users.id], to: [relations.session.userId] }),
    apiKeys: relations.many.apiKeys({ from: [relations.users.id], to: [relations.apiKeys.createdByUserId] }),
    inAppAgentConversations: relations.many.inAppAgentConversations({ from: [relations.users.id], to: [relations.inAppAgentConversations.createdByUserId] }),
    inAppAgentRuns: relations.many.inAppAgentRuns({ from: [relations.users.id], to: [relations.inAppAgentRuns.triggeredByUserId] }),
    organizationMemberships: relations.many.organizationMemberships({ from: [relations.users.id], to: [relations.organizationMemberships.userId] }),
    projectMemberships: relations.many.projectMemberships({ from: [relations.users.id], to: [relations.projectMemberships.userId] }),
    membershipInvitations: relations.many.membershipInvitations({ from: [relations.users.id], to: [relations.membershipInvitations.invitedByUserId] }),
    annotationQueueItems_annotatorUserId: relations.many.annotationQueueItems({ from: [relations.users.id], to: [relations.annotationQueueItems.annotatorUserId], alias: "annotationQueueItems_annotatorUserId_users_id" }),
    annotationQueueItems_lockedByUserId: relations.many.annotationQueueItems({ from: [relations.users.id], to: [relations.annotationQueueItems.lockedByUserId], alias: "annotationQueueItems_lockedByUserId_users_id" }),
    annotationQueueAssignments: relations.many.annotationQueueAssignments({ from: [relations.users.id], to: [relations.annotationQueueAssignments.userId] }),
    commentReactions: relations.many.commentReactions({ from: [relations.users.id], to: [relations.commentReactions.userId] }),
    notificationPreferences: relations.many.notificationPreferences({ from: [relations.users.id], to: [relations.notificationPreferences.userId] }),
    dashboards_updatedBy: relations.many.dashboards({ from: [relations.users.id], to: [relations.dashboards.updatedBy], alias: "dashboards_updatedBy_users_id" }),
    dashboards_createdBy: relations.many.dashboards({ from: [relations.users.id], to: [relations.dashboards.createdBy], alias: "dashboards_createdBy_users_id" }),
    dashboardWidgets_updatedBy: relations.many.dashboardWidgets({ from: [relations.users.id], to: [relations.dashboardWidgets.updatedBy], alias: "dashboardWidgets_updatedBy_users_id" }),
    dashboardWidgets_createdBy: relations.many.dashboardWidgets({ from: [relations.users.id], to: [relations.dashboardWidgets.createdBy], alias: "dashboardWidgets_createdBy_users_id" }),
    tableViewPresets_updatedBy: relations.many.tableViewPresets({ from: [relations.users.id], to: [relations.tableViewPresets.updatedBy], alias: "tableViewPresets_updatedBy_users_id" }),
    tableViewPresets_createdBy: relations.many.tableViewPresets({ from: [relations.users.id], to: [relations.tableViewPresets.createdBy], alias: "tableViewPresets_createdBy_users_id" }),
    defaultViews: relations.many.defaultViews({ from: [relations.users.id], to: [relations.defaultViews.userId] }),
    monitors_updatedBy: relations.many.monitors({ from: [relations.users.id], to: [relations.monitors.updatedBy], alias: "monitors_updatedBy_users_id" }),
    monitors_createdBy: relations.many.monitors({ from: [relations.users.id], to: [relations.monitors.createdBy], alias: "monitors_createdBy_users_id" }),
    surveys: relations.many.surveys({ from: [relations.users.id], to: [relations.surveys.userId] }),
  },
  session: {
    user: relations.one.users({ from: [relations.session.userId], to: [relations.users.id] }),
  },
  projects: {
    organization: relations.one.organizations({ from: [relations.projects.orgId], to: [relations.organizations.id] }),
    dashboard: relations.one.dashboards({ from: [relations.projects.homeDashboardId], to: [relations.dashboards.id], alias: "projects_homeDashboardId_dashboards_id" }),
    apiKeys: relations.many.apiKeys({ from: [relations.projects.id], to: [relations.apiKeys.projectId] }),
    inAppAgentConversations: relations.many.inAppAgentConversations({ from: [relations.projects.id], to: [relations.inAppAgentConversations.projectId] }),
    inAppAgentEvents: relations.many.inAppAgentEvents({ from: [relations.projects.id], to: [relations.inAppAgentEvents.projectId] }),
    inAppAgentRuns: relations.many.inAppAgentRuns({ from: [relations.projects.id], to: [relations.inAppAgentRuns.projectId] }),
    inAppAgentPendingToolApprovals: relations.many.inAppAgentPendingToolApprovals({ from: [relations.projects.id], to: [relations.inAppAgentPendingToolApprovals.projectId] }),
    llmApiKeys: relations.many.llmApiKeys({ from: [relations.projects.id], to: [relations.llmApiKeys.projectId] }),
    projectMemberships: relations.many.projectMemberships({ from: [relations.projects.id], to: [relations.projectMemberships.projectId] }),
    membershipInvitations: relations.many.membershipInvitations({ from: [relations.projects.id], to: [relations.membershipInvitations.projectId] }),
    traceSessions: relations.many.traceSessions({ from: [relations.projects.id], to: [relations.traceSessions.projectId] }),
    scoreConfigs: relations.many.scoreConfigs({ from: [relations.projects.id], to: [relations.scoreConfigs.projectId] }),
    annotationQueues: relations.many.annotationQueues({ from: [relations.projects.id], to: [relations.annotationQueues.projectId] }),
    annotationQueueItems: relations.many.annotationQueueItems({ from: [relations.projects.id], to: [relations.annotationQueueItems.projectId] }),
    annotationQueueAssignments: relations.many.annotationQueueAssignments({ from: [relations.projects.id], to: [relations.annotationQueueAssignments.projectId] }),
    datasets: relations.many.datasets({ from: [relations.projects.id], to: [relations.datasets.projectId] }),
    comments: relations.many.comments({ from: [relations.projects.id], to: [relations.comments.projectId] }),
    commentReactions: relations.many.commentReactions({ from: [relations.projects.id], to: [relations.commentReactions.projectId] }),
    notificationPreferences: relations.many.notificationPreferences({ from: [relations.projects.id], to: [relations.notificationPreferences.projectId] }),
    prompts: relations.many.prompts({ from: [relations.projects.id], to: [relations.prompts.projectId] }),
    promptDependencies: relations.many.promptDependencies({ from: [relations.projects.id], to: [relations.promptDependencies.projectId] }),
    promptProtectedLabels: relations.many.promptProtectedLabels({ from: [relations.projects.id], to: [relations.promptProtectedLabels.projectId] }),
    models: relations.many.models({ from: [relations.projects.id], to: [relations.models.projectId] }),
    prices: relations.many.prices({ from: [relations.projects.id], to: [relations.prices.projectId] }),
    evalTemplates: relations.many.evalTemplates({ from: [relations.projects.id], to: [relations.evalTemplates.projectId] }),
    jobConfigurations: relations.many.jobConfigurations({ from: [relations.projects.id], to: [relations.jobConfigurations.projectId] }),
    jobExecutions: relations.many.jobExecutions({ from: [relations.projects.id], to: [relations.jobExecutions.projectId] }),
    defaultLlmModels: relations.many.defaultLlmModels({ from: [relations.projects.id], to: [relations.defaultLlmModels.projectId] }),
    posthogIntegrations: relations.many.posthogIntegrations({ from: [relations.projects.id], to: [relations.posthogIntegrations.projectId] }),
    mixpanelIntegrations: relations.many.mixpanelIntegrations({ from: [relations.projects.id], to: [relations.mixpanelIntegrations.projectId] }),
    blobStorageIntegrations: relations.many.blobStorageIntegrations({ from: [relations.projects.id], to: [relations.blobStorageIntegrations.projectId] }),
    webCalloutEndpoints: relations.many.webCalloutEndpoints({ from: [relations.projects.id], to: [relations.webCalloutEndpoints.projectId] }),
    batchExports: relations.many.batchExports({ from: [relations.projects.id], to: [relations.batchExports.projectId] }),
    batchActions: relations.many.batchActions({ from: [relations.projects.id], to: [relations.batchActions.projectId] }),
    media: relations.many.media({ from: [relations.projects.id], to: [relations.media.projectId] }),
    llmSchemas: relations.many.llmSchemas({ from: [relations.projects.id], to: [relations.llmSchemas.projectId] }),
    llmTools: relations.many.llmTools({ from: [relations.projects.id], to: [relations.llmTools.projectId] }),
    dashboards: relations.many.dashboards({ from: [relations.projects.id], to: [relations.dashboards.projectId], alias: "dashboards_projectId_projects_id" }),
    dashboardWidgets: relations.many.dashboardWidgets({ from: [relations.projects.id], to: [relations.dashboardWidgets.projectId] }),
    tableViewPresets: relations.many.tableViewPresets({ from: [relations.projects.id], to: [relations.tableViewPresets.projectId] }),
    defaultViews: relations.many.defaultViews({ from: [relations.projects.id], to: [relations.defaultViews.projectId] }),
    actions: relations.many.actions({ from: [relations.projects.id], to: [relations.actions.projectId] }),
    triggers: relations.many.triggers({ from: [relations.projects.id], to: [relations.triggers.projectId] }),
    automations: relations.many.automations({ from: [relations.projects.id], to: [relations.automations.projectId] }),
    automationExecutions: relations.many.automationExecutions({ from: [relations.projects.id], to: [relations.automationExecutions.projectId] }),
    monitors: relations.many.monitors({ from: [relations.projects.id], to: [relations.monitors.projectId] }),
    slackIntegrations: relations.many.slackIntegrations({ from: [relations.projects.id], to: [relations.slackIntegrations.projectId] }),
    pendingDeletions: relations.many.pendingDeletions({ from: [relations.projects.id], to: [relations.pendingDeletions.projectId] }),
  },
  organizations: {
    projects: relations.many.projects({ from: [relations.organizations.id], to: [relations.projects.orgId] }),
    apiKeys: relations.many.apiKeys({ from: [relations.organizations.id], to: [relations.apiKeys.organizationId] }),
    organizationMemberships: relations.many.organizationMemberships({ from: [relations.organizations.id], to: [relations.organizationMemberships.orgId] }),
    membershipInvitations: relations.many.membershipInvitations({ from: [relations.organizations.id], to: [relations.membershipInvitations.orgId] }),
    verifiedDomains: relations.many.verifiedDomains({ from: [relations.organizations.id], to: [relations.verifiedDomains.organizationId] }),
    surveys: relations.many.surveys({ from: [relations.organizations.id], to: [relations.surveys.orgId] }),
    cloudSpendAlerts: relations.many.cloudSpendAlerts({ from: [relations.organizations.id], to: [relations.cloudSpendAlerts.orgId] }),
  },
  dashboards: {
    projects: relations.many.projects({ from: [relations.dashboards.id], to: [relations.projects.homeDashboardId], alias: "projects_homeDashboardId_dashboards_id" }),
    project: relations.one.projects({ from: [relations.dashboards.projectId], to: [relations.projects.id], alias: "dashboards_projectId_projects_id" }),
    user_updatedBy: relations.one.users({ from: [relations.dashboards.updatedBy], to: [relations.users.id], alias: "dashboards_updatedBy_users_id" }),
    user_createdBy: relations.one.users({ from: [relations.dashboards.createdBy], to: [relations.users.id], alias: "dashboards_createdBy_users_id" }),
  },
  apiKeys: {
    apiKey: relations.one.apiKeys({ from: [relations.apiKeys.createdByApiKeyId], to: [relations.apiKeys.id], alias: "apiKeys_createdByApiKeyId_apiKeys_id" }),
    apiKeys: relations.many.apiKeys({ from: [relations.apiKeys.id], to: [relations.apiKeys.createdByApiKeyId], alias: "apiKeys_createdByApiKeyId_apiKeys_id" }),
    user: relations.one.users({ from: [relations.apiKeys.createdByUserId], to: [relations.users.id] }),
    organization: relations.one.organizations({ from: [relations.apiKeys.organizationId], to: [relations.organizations.id] }),
    project: relations.one.projects({ from: [relations.apiKeys.projectId], to: [relations.projects.id] }),
  },
  inAppAgentConversations: {
    user: relations.one.users({ from: [relations.inAppAgentConversations.createdByUserId], to: [relations.users.id] }),
    project: relations.one.projects({ from: [relations.inAppAgentConversations.projectId], to: [relations.projects.id] }),
    inAppAgentEvents: relations.many.inAppAgentEvents({ from: [relations.inAppAgentConversations.id], to: [relations.inAppAgentEvents.conversationId] }),
    inAppAgentRuns: relations.many.inAppAgentRuns({ from: [relations.inAppAgentConversations.id], to: [relations.inAppAgentRuns.conversationId] }),
    inAppAgentPendingToolApprovals: relations.many.inAppAgentPendingToolApprovals({ from: [relations.inAppAgentConversations.id], to: [relations.inAppAgentPendingToolApprovals.conversationId] }),
  },
  inAppAgentEvents: {
    inAppAgentRun: relations.one.inAppAgentRuns({ from: [relations.inAppAgentEvents.runId], to: [relations.inAppAgentRuns.id] }),
    inAppAgentConversation: relations.one.inAppAgentConversations({ from: [relations.inAppAgentEvents.conversationId], to: [relations.inAppAgentConversations.id] }),
    project: relations.one.projects({ from: [relations.inAppAgentEvents.projectId], to: [relations.projects.id] }),
  },
  inAppAgentRuns: {
    inAppAgentEvents: relations.many.inAppAgentEvents({ from: [relations.inAppAgentRuns.id], to: [relations.inAppAgentEvents.runId] }),
    user: relations.one.users({ from: [relations.inAppAgentRuns.triggeredByUserId], to: [relations.users.id] }),
    inAppAgentConversation: relations.one.inAppAgentConversations({ from: [relations.inAppAgentRuns.conversationId], to: [relations.inAppAgentConversations.id] }),
    project: relations.one.projects({ from: [relations.inAppAgentRuns.projectId], to: [relations.projects.id] }),
  },
  inAppAgentPendingToolApprovals: {
    inAppAgentConversation: relations.one.inAppAgentConversations({ from: [relations.inAppAgentPendingToolApprovals.conversationId], to: [relations.inAppAgentConversations.id] }),
    project: relations.one.projects({ from: [relations.inAppAgentPendingToolApprovals.projectId], to: [relations.projects.id] }),
  },
  llmApiKeys: {
    project: relations.one.projects({ from: [relations.llmApiKeys.projectId], to: [relations.projects.id] }),
    defaultLlmModels: relations.many.defaultLlmModels({ from: [relations.llmApiKeys.id], to: [relations.defaultLlmModels.llmApiKeyId] }),
  },
  organizationMemberships: {
    user: relations.one.users({ from: [relations.organizationMemberships.userId], to: [relations.users.id] }),
    organization: relations.one.organizations({ from: [relations.organizationMemberships.orgId], to: [relations.organizations.id] }),
    projectMemberships: relations.many.projectMemberships({ from: [relations.organizationMemberships.id], to: [relations.projectMemberships.orgMembershipId] }),
  },
  projectMemberships: {
    user: relations.one.users({ from: [relations.projectMemberships.userId], to: [relations.users.id] }),
    project: relations.one.projects({ from: [relations.projectMemberships.projectId], to: [relations.projects.id] }),
    organizationMembership: relations.one.organizationMemberships({ from: [relations.projectMemberships.orgMembershipId], to: [relations.organizationMemberships.id] }),
  },
  membershipInvitations: {
    user: relations.one.users({ from: [relations.membershipInvitations.invitedByUserId], to: [relations.users.id] }),
    project: relations.one.projects({ from: [relations.membershipInvitations.projectId], to: [relations.projects.id] }),
    organization: relations.one.organizations({ from: [relations.membershipInvitations.orgId], to: [relations.organizations.id] }),
  },
  traceSessions: {
    project: relations.one.projects({ from: [relations.traceSessions.projectId], to: [relations.projects.id] }),
  },
  scoreConfigs: {
    project: relations.one.projects({ from: [relations.scoreConfigs.projectId], to: [relations.projects.id] }),
  },
  annotationQueues: {
    project: relations.one.projects({ from: [relations.annotationQueues.projectId], to: [relations.projects.id] }),
    annotationQueueItems: relations.many.annotationQueueItems({ from: [relations.annotationQueues.id], to: [relations.annotationQueueItems.queueId] }),
    annotationQueueAssignments: relations.many.annotationQueueAssignments({ from: [relations.annotationQueues.id], to: [relations.annotationQueueAssignments.queueId] }),
  },
  annotationQueueItems: {
    project: relations.one.projects({ from: [relations.annotationQueueItems.projectId], to: [relations.projects.id] }),
    user_annotatorUserId: relations.one.users({ from: [relations.annotationQueueItems.annotatorUserId], to: [relations.users.id], alias: "annotationQueueItems_annotatorUserId_users_id" }),
    user_lockedByUserId: relations.one.users({ from: [relations.annotationQueueItems.lockedByUserId], to: [relations.users.id], alias: "annotationQueueItems_lockedByUserId_users_id" }),
    annotationQueue: relations.one.annotationQueues({ from: [relations.annotationQueueItems.queueId], to: [relations.annotationQueues.id] }),
  },
  annotationQueueAssignments: {
    annotationQueue: relations.one.annotationQueues({ from: [relations.annotationQueueAssignments.queueId], to: [relations.annotationQueues.id] }),
    user: relations.one.users({ from: [relations.annotationQueueAssignments.userId], to: [relations.users.id] }),
    project: relations.one.projects({ from: [relations.annotationQueueAssignments.projectId], to: [relations.projects.id] }),
  },
  datasets: {
    project: relations.one.projects({ from: [relations.datasets.projectId], to: [relations.projects.id] }),
    datasetItems: relations.many.datasetItems({ from: [relations.datasets.id], to: [relations.datasetItems.datasetId] }),
    datasetRuns: relations.many.datasetRuns({ from: [relations.datasets.id], to: [relations.datasetRuns.datasetId] }),
  },
  datasetItems: {
    dataset: relations.one.datasets({ from: [relations.datasetItems.datasetId], to: [relations.datasets.id] }),
  },
  datasetRuns: {
    dataset: relations.one.datasets({ from: [relations.datasetRuns.datasetId], to: [relations.datasets.id] }),
  },
  comments: {
    project: relations.one.projects({ from: [relations.comments.projectId], to: [relations.projects.id] }),
    commentReactions: relations.many.commentReactions({ from: [relations.comments.id], to: [relations.commentReactions.commentId] }),
  },
  commentReactions: {
    user: relations.one.users({ from: [relations.commentReactions.userId], to: [relations.users.id] }),
    comment: relations.one.comments({ from: [relations.commentReactions.commentId], to: [relations.comments.id] }),
    project: relations.one.projects({ from: [relations.commentReactions.projectId], to: [relations.projects.id] }),
  },
  notificationPreferences: {
    project: relations.one.projects({ from: [relations.notificationPreferences.projectId], to: [relations.projects.id] }),
    user: relations.one.users({ from: [relations.notificationPreferences.userId], to: [relations.users.id] }),
  },
  prompts: {
    project: relations.one.projects({ from: [relations.prompts.projectId], to: [relations.projects.id] }),
    promptDependencies: relations.many.promptDependencies({ from: [relations.prompts.id], to: [relations.promptDependencies.parentId] }),
  },
  promptDependencies: {
    prompt: relations.one.prompts({ from: [relations.promptDependencies.parentId], to: [relations.prompts.id] }),
    project: relations.one.projects({ from: [relations.promptDependencies.projectId], to: [relations.projects.id] }),
  },
  promptProtectedLabels: {
    project: relations.one.projects({ from: [relations.promptProtectedLabels.projectId], to: [relations.projects.id] }),
  },
  models: {
    project: relations.one.projects({ from: [relations.models.projectId], to: [relations.projects.id] }),
    prices: relations.many.prices({ from: [relations.models.id], to: [relations.prices.modelId] }),
    pricingTiers: relations.many.pricingTiers({ from: [relations.models.id], to: [relations.pricingTiers.modelId] }),
  },
  prices: {
    pricingTier: relations.one.pricingTiers({ from: [relations.prices.pricingTierId], to: [relations.pricingTiers.id] }),
    project: relations.one.projects({ from: [relations.prices.projectId], to: [relations.projects.id] }),
    model: relations.one.models({ from: [relations.prices.modelId], to: [relations.models.id] }),
  },
  pricingTiers: {
    prices: relations.many.prices({ from: [relations.pricingTiers.id], to: [relations.prices.pricingTierId] }),
    model: relations.one.models({ from: [relations.pricingTiers.modelId], to: [relations.models.id] }),
  },
  evalTemplates: {
    project: relations.one.projects({ from: [relations.evalTemplates.projectId], to: [relations.projects.id] }),
    jobConfigurations: relations.many.jobConfigurations({ from: [relations.evalTemplates.id], to: [relations.jobConfigurations.evalTemplateId] }),
  },
  jobConfigurations: {
    evalTemplate: relations.one.evalTemplates({ from: [relations.jobConfigurations.evalTemplateId], to: [relations.evalTemplates.id] }),
    project: relations.one.projects({ from: [relations.jobConfigurations.projectId], to: [relations.projects.id] }),
    jobExecutions: relations.many.jobExecutions({ from: [relations.jobConfigurations.id], to: [relations.jobExecutions.jobConfigurationId] }),
  },
  jobExecutions: {
    jobConfiguration: relations.one.jobConfigurations({ from: [relations.jobExecutions.jobConfigurationId], to: [relations.jobConfigurations.id] }),
    project: relations.one.projects({ from: [relations.jobExecutions.projectId], to: [relations.projects.id] }),
  },
  defaultLlmModels: {
    llmApiKey: relations.one.llmApiKeys({ from: [relations.defaultLlmModels.llmApiKeyId], to: [relations.llmApiKeys.id] }),
    project: relations.one.projects({ from: [relations.defaultLlmModels.projectId], to: [relations.projects.id] }),
  },
  verifiedDomains: {
    organization: relations.one.organizations({ from: [relations.verifiedDomains.organizationId], to: [relations.organizations.id] }),
  },
  posthogIntegrations: {
    project: relations.one.projects({ from: [relations.posthogIntegrations.projectId], to: [relations.projects.id] }),
  },
  mixpanelIntegrations: {
    project: relations.one.projects({ from: [relations.mixpanelIntegrations.projectId], to: [relations.projects.id] }),
  },
  blobStorageIntegrations: {
    project: relations.one.projects({ from: [relations.blobStorageIntegrations.projectId], to: [relations.projects.id] }),
  },
  webCalloutEndpoints: {
    project: relations.one.projects({ from: [relations.webCalloutEndpoints.projectId], to: [relations.projects.id] }),
  },
  batchExports: {
    project: relations.one.projects({ from: [relations.batchExports.projectId], to: [relations.projects.id] }),
  },
  batchActions: {
    project: relations.one.projects({ from: [relations.batchActions.projectId], to: [relations.projects.id] }),
  },
  media: {
    project: relations.one.projects({ from: [relations.media.projectId], to: [relations.projects.id] }),
  },
  llmSchemas: {
    project: relations.one.projects({ from: [relations.llmSchemas.projectId], to: [relations.projects.id] }),
  },
  llmTools: {
    project: relations.one.projects({ from: [relations.llmTools.projectId], to: [relations.projects.id] }),
  },
  dashboardWidgets: {
    project: relations.one.projects({ from: [relations.dashboardWidgets.projectId], to: [relations.projects.id] }),
    user_updatedBy: relations.one.users({ from: [relations.dashboardWidgets.updatedBy], to: [relations.users.id], alias: "dashboardWidgets_updatedBy_users_id" }),
    user_createdBy: relations.one.users({ from: [relations.dashboardWidgets.createdBy], to: [relations.users.id], alias: "dashboardWidgets_createdBy_users_id" }),
  },
  tableViewPresets: {
    user_updatedBy: relations.one.users({ from: [relations.tableViewPresets.updatedBy], to: [relations.users.id], alias: "tableViewPresets_updatedBy_users_id" }),
    user_createdBy: relations.one.users({ from: [relations.tableViewPresets.createdBy], to: [relations.users.id], alias: "tableViewPresets_createdBy_users_id" }),
    project: relations.one.projects({ from: [relations.tableViewPresets.projectId], to: [relations.projects.id] }),
  },
  defaultViews: {
    user: relations.one.users({ from: [relations.defaultViews.userId], to: [relations.users.id] }),
    project: relations.one.projects({ from: [relations.defaultViews.projectId], to: [relations.projects.id] }),
  },
  actions: {
    project: relations.one.projects({ from: [relations.actions.projectId], to: [relations.projects.id] }),
    automations: relations.many.automations({ from: [relations.actions.id], to: [relations.automations.actionId] }),
    automationExecutions: relations.many.automationExecutions({ from: [relations.actions.id], to: [relations.automationExecutions.actionId] }),
  },
  triggers: {
    project: relations.one.projects({ from: [relations.triggers.projectId], to: [relations.projects.id] }),
    automations: relations.many.automations({ from: [relations.triggers.id], to: [relations.automations.triggerId] }),
    automationExecutions: relations.many.automationExecutions({ from: [relations.triggers.id], to: [relations.automationExecutions.triggerId] }),
  },
  automations: {
    project: relations.one.projects({ from: [relations.automations.projectId], to: [relations.projects.id] }),
    action: relations.one.actions({ from: [relations.automations.actionId], to: [relations.actions.id] }),
    trigger: relations.one.triggers({ from: [relations.automations.triggerId], to: [relations.triggers.id] }),
    automationExecutions: relations.many.automationExecutions({ from: [relations.automations.id], to: [relations.automationExecutions.automationId] }),
  },
  automationExecutions: {
    project: relations.one.projects({ from: [relations.automationExecutions.projectId], to: [relations.projects.id] }),
    action: relations.one.actions({ from: [relations.automationExecutions.actionId], to: [relations.actions.id] }),
    trigger: relations.one.triggers({ from: [relations.automationExecutions.triggerId], to: [relations.triggers.id] }),
    automation: relations.one.automations({ from: [relations.automationExecutions.automationId], to: [relations.automations.id] }),
  },
  monitors: {
    project: relations.one.projects({ from: [relations.monitors.projectId], to: [relations.projects.id] }),
    user_updatedBy: relations.one.users({ from: [relations.monitors.updatedBy], to: [relations.users.id], alias: "monitors_updatedBy_users_id" }),
    user_createdBy: relations.one.users({ from: [relations.monitors.createdBy], to: [relations.users.id], alias: "monitors_createdBy_users_id" }),
  },
  slackIntegrations: {
    project: relations.one.projects({ from: [relations.slackIntegrations.projectId], to: [relations.projects.id] }),
  },
  pendingDeletions: {
    project: relations.one.projects({ from: [relations.pendingDeletions.projectId], to: [relations.projects.id] }),
  },
  surveys: {
    user: relations.one.users({ from: [relations.surveys.userId], to: [relations.users.id] }),
    organization: relations.one.organizations({ from: [relations.surveys.orgId], to: [relations.organizations.id] }),
  },
  cloudSpendAlerts: {
    organization: relations.one.organizations({ from: [relations.cloudSpendAlerts.orgId], to: [relations.organizations.id] }),
  },
}));
